language: ruby
rvm:
 - 2.2
addons:
  code_climate:
    repo_token: 8d4e8b55667232d1a2a389baa9a7d009fc11a093d8a9e6c143f78a9647802efb
script:
  - bundle exec rspec
after_script:
  - bundle exec codeclimate-test-reporter
